### ISSUE TITLE
Cocoapods Podspec needs updating (1.0.4)

### ISSUE THREAD

**Issue by twhitt14** [Coeur/CollectionViewCenteredFlowLayout#10]
Hi, thanks for the great library by the way. Could you please update the podspec so we can update to 1.0.4 with a simple `pod update CollectionViewCenteredFlowLayout`?

**Comment by Coeur** [comment]
I stopped using Cocoapods a few years ago... so I'm afraid for now you'll have to configure your podfile to point explicitly at the repository's main branch directly.

**Comment by justinkumpe** [comment]
Pointing explicitly at the repo works but can be a pain as it downloads the repo each time you pod install or pod update just to check if it needs to be updated.

I can live with it but would you be open to one of the following?

- setup your repo to auto push new versions to CocoaPods. Once setup all you would need to do is push a new tag to GitHub to trigger the workflow (https://github.com/marketplace/actions/deploy-to-cocoapod-action)
- add a contributor to CocoaPods for this project that can push new versions to CocoaPods (https://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors)
- allow someone to "claim" your plugin on CocoaPods so they may push new versions to CocoaPods leaving you listed as the author and pointing to your GitHub repo (https://guides.cocoapods.org/making/getting-setup-with-trunk.html#claiming-an-existing-library)

**Comment by Coeur** [comment]
CocoaPods is moving to read-only and all devs should migrate to Swift Package Manager:
https://blog.cocoapods.org/CocoaPods-Support-Plans/
