### ISSUE TITLE
Compile errors on Xcode 14

### ISSUE THREAD

**Issue by chamitha** [Coeur/CollectionViewCenteredFlowLayout#11]
Several occurrences of 
`Type of expression is ambiguous without more context`
and
`The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions`
errors occur when compiling in Xcode 14

**Comment by Coeur** [comment]
Wasn't it fixed with #7 ? You should try the latest commit.

**Comment by chamitha** [comment]
I use Cocoapods and had
`pod 'CollectionViewCenteredFlowLayout'` in my Podfile
updating that to the latest commit as suggested resolves the issue.
`pod 'CollectionViewCenteredFlowLayout', git: 'https://github.com/Coeur/CollectionViewCenteredFlowLayout', commit: '420df83f1586ae2a1fb1bdd36870b9ea50a9fab4'`
